#!/usr/bin/env python
# ________  ___    ___ ________ _______  _________  ________  ___  ___
#|\   __  \|\  \  /  /|\  _____\\  ___ \|\___   ___\\   ____\|\  \|\  \
#\ \  \|\  \ \  \/  / | \  \__/\ \   __/\|___ \  \_\ \  \___|\ \  \\\  \
# \ \   ____\ \    / / \ \   __\\ \  \_|/__  \ \  \ \ \  \    \ \   __  \
#  \ \  \___|\/  /  /   \ \  \_| \ \  \_|\ \  \ \  \ \ \  \____\ \  \ \  \
#   \ \__\ __/  / /      \ \__\   \ \_______\  \ \__\ \ \_______\ \__\ \__\
#    \|__||\___/ /        \|__|    \|_______|   \|__|  \|_______|\|__|\|__|
#         \|___|/
# Made by Kreato
# Licensed Under GPL3-Or-Later
import fontawesome as fa
import platform, psutil, os, getpass, shutil
uname = platform.uname()
cpu = psutil.cpu_percent()
username = getpass.getuser()
ram = psutil.virtual_memory()
used = ram.used // (2**30)
total = ram.total // (2**30)
totaldisk, useddisk, freedisk = shutil.disk_usage("/")
diskpercent_used = round(useddisk / totaldisk * 100, 2)
percent_used = round(ram.used / ram.total * 100, 2)
print(f"{fa.icons['hdd']}  {useddisk // (2**30)}GiB / {freedisk // (2**30)}GiB ({diskpercent_used}%)")
print(f"{fa.icons['desktop']}  {username}@{uname.node}")
print(f"{fa.icons['microchip']}  {uname.processor} ({cpu}%) ")
print(f"{fa.icons['memory']}  {used}GiB / {total}GiB ({percent_used}%)")
if os.name == 'posix':
    print(f"{fa.icons['linux']}  GNU\{uname.system} {uname.release}")
elif os.name == 'nt':
    print(f"{fa.icons['windows']}  {uname.system} {uname.release}")
